# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'poses.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_TrackTime(object):
    def setupUi(self, TrackTime):
        TrackTime.setObjectName("TrackTime")
        TrackTime.resize(905, 741)
        TrackTime.setAutoFillBackground(False)
        TrackTime.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(TrackTime)
        self.centralwidget.setStyleSheet("QPushButton{\n"
                                         "background-color: rgb(42,42,42);\n"
                                         "    color: rgb(255, 255, 255);\n"
                                         "border-width:2px;\n"
                                         "border-style:solid;\n"
                                         "border-color: rgb(255, 255, 255);\n"
                                         "border-radius: 10px;\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton::hover\n"
                                         "{\n"
                                         "   \n"
                                         "    color: rgb(30, 30, 30);\n"
                                         "    background-color: rgba(92,201,107,255);\n"
                                         "}\n"
                                         "\n"
                                         "")
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 411, 131))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("images/header.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.btn_sp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sp.setGeometry(QtCore.QRect(250, 660, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(12)
        self.btn_sp.setFont(font)
        self.btn_sp.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sp.setIcon(icon)
        self.btn_sp.setObjectName("btn_sp")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 150, 851, 16))
        self.line.setStyleSheet("color:rgba(92,201,107,255);\n"
                                "border-color: rgba(92,201,107,255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btn_home = QtWidgets.QPushButton(self.centralwidget)
        self.btn_home.setGeometry(QtCore.QRect(750, 50, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(12)
        self.btn_home.setFont(font)
        self.btn_home.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_home.setIcon(icon1)
        self.btn_home.setObjectName("btn_home")
        self.logo_2 = QtWidgets.QLabel(self.centralwidget)
        self.logo_2.setGeometry(QtCore.QRect(30, 170, 841, 561))
        self.logo_2.setText("")
        self.logo_2.setPixmap(QtGui.QPixmap("images/poses.jpg"))
        self.logo_2.setScaledContents(True)
        self.logo_2.setObjectName("logo_2")
        self.btn_s = QtWidgets.QPushButton(self.centralwidget)
        self.btn_s.setGeometry(QtCore.QRect(250, 360, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(12)
        self.btn_s.setFont(font)
        self.btn_s.setStyleSheet("")
        self.btn_s.setIcon(icon)
        self.btn_s.setObjectName("btn_s")
        self.btn_tt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tt.setGeometry(QtCore.QRect(690, 500, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(12)
        self.btn_tt.setFont(font)
        self.btn_tt.setStyleSheet("")
        self.btn_tt.setIcon(icon)
        self.btn_tt.setObjectName("btn_tt")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 330, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: transparent;\n"
                                 "color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.lbl_s = QtWidgets.QLabel(self.centralwidget)
        self.lbl_s.setGeometry(QtCore.QRect(290, 330, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.lbl_s.setFont(font)
        self.lbl_s.setStyleSheet("background-color: transparent;\n"
                                 "color: rgb(255, 255, 255);")
        self.lbl_s.setObjectName("lbl_s")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(690, 470, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: transparent;\n"
                                   "color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.lbl_tt = QtWidgets.QLabel(self.centralwidget)
        self.lbl_tt.setGeometry(QtCore.QRect(730, 470, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.lbl_tt.setFont(font)
        self.lbl_tt.setStyleSheet("background-color: transparent;\n"
                                  "color: rgb(255, 255, 255);")
        self.lbl_tt.setObjectName("lbl_tt")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 630, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: transparent;\n"
                                   "color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.lbl_sp = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sp.setGeometry(QtCore.QRect(290, 630, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.lbl_sp.setFont(font)
        self.lbl_sp.setStyleSheet("background-color: transparent;\n"
                                  "color: rgb(255, 255, 255);")
        self.lbl_sp.setObjectName("lbl_sp")
        self.logo_2.raise_()
        self.logo.raise_()
        self.line.raise_()
        self.btn_home.raise_()
        self.btn_sp.raise_()
        self.btn_s.raise_()
        self.btn_tt.raise_()
        self.label.raise_()
        self.lbl_s.raise_()
        self.label_3.raise_()
        self.lbl_tt.raise_()
        self.label_5.raise_()
        self.lbl_sp.raise_()
        TrackTime.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TrackTime)
        self.statusbar.setObjectName("statusbar")
        TrackTime.setStatusBar(self.statusbar)

        self.retranslateUi(TrackTime)
        QtCore.QMetaObject.connectSlotsByName(TrackTime)

        f = open("squats.txt", "r")
        squat_count = f.read()
        self.lbl_s.setText(str(squat_count))

        f = open("toetouch.txt", "r")
        toe_touch_count = f.read()
        self.lbl_tt.setText(str(toe_touch_count))

        f = open("shoulderpress.txt", "r")
        shoulder_press_count = f.read()
        self.lbl_sp.setText(str(shoulder_press_count))

        self.btn_sp.clicked.connect(self.load_sp)
        self.btn_s.clicked.connect(self.load_s)
        self.btn_tt.clicked.connect(self.load_tt)
        self.btn_home.clicked.connect(self.closeIt)

    def load_sp(self):
        os.system("python pose_estimation_shoulderpress.py")
        self.retranslateUi(TrackTime)

    def load_s(self):
        os.system("python pose_estimation_squats.py")
        self.retranslateUi(TrackTime)

    def load_tt(self):
        os.system("python pose_estimation_toetouch.py")
        self.retranslateUi(TrackTime)

    def closeIt(self):
            self.close()

    def retranslateUi(self, TrackTime):
        _translate = QtCore.QCoreApplication.translate
        TrackTime.setWindowTitle(_translate("TrackTime", "Main Menu"))
        self.btn_sp.setText(_translate("TrackTime", "Start"))
        self.btn_home.setText(_translate("TrackTime", "Home"))
        self.btn_s.setText(_translate("TrackTime", "Start"))
        self.btn_tt.setText(_translate("TrackTime", "Start"))
        self.label.setText(_translate("TrackTime", "Last"))
        self.lbl_s.setText(_translate("TrackTime", "2"))
        self.label_3.setText(_translate("TrackTime", "Last"))
        self.lbl_tt.setText(_translate("TrackTime", "2"))
        self.label_5.setText(_translate("TrackTime", "Last"))
        self.lbl_sp.setText(_translate("TrackTime", "2"))

        f = open("squats.txt", "r")
        squat_count = f.read()
        self.lbl_s.setText(str(squat_count))

        f = open("toetouch.txt", "r")
        toe_touch_count = f.read()
        self.lbl_tt.setText(str(toe_touch_count))

        f = open("shoulderpress.txt", "r")
        shoulder_press_count = f.read()
        self.lbl_sp.setText(str(shoulder_press_count))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    TrackTime = QtWidgets.QMainWindow()
    ui = Ui_TrackTime()
    ui.setupUi(TrackTime)
    TrackTime.show()
    sys.exit(app.exec_())
